version: "3.7"
services:
    database-pg:
      image: postgres
      container_name: database-pg
      restart: always
      environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_USER: docker
        POSTGRES_DB: pg-teste
      volumes: 
        - /pgdata:/var/lib/postgressql/data
      ports:
        - '5432:5432'

    app:
      build: .
      container_name: api-typeorm
      restart: always
      ports:
        - 3333:3333
      volumes:
        - .:/usr/app
      links:
        - database-pg
      depends_on:
        - database-pg